config/routes.rb
Rails.application.routes.draw do
  resources :external_subscriptions
  resources :subscriptions
  resources :investors
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/external_subscription.rb
class ExternalSubscription < ApplicationRecord
  belongs_to :project
  belongs_to :investor
end

app/controllers/external_subscriptions_controller.rb
class ExternalSubscriptionsController < ApplicationController
  before_action :set_external_subscription, only: [:show, :edit, :update, :destroy]

  # GET /external_subscriptions
  # GET /external_subscriptions.json
  def index
    @external_subscriptions = ExternalSubscription.all
  end

  # GET /external_subscriptions/1
  # GET /external_subscriptions/1.json
  def show
  end

  # GET /external_subscriptions/new
  def new
    @external_subscription = ExternalSubscription.new
  end

  # GET /external_subscriptions/1/edit
  def edit
  end

  # POST /external_subscriptions
  # POST /external_subscriptions.json
  def create
    @external_subscription = ExternalSubscription.new(external_subscription_params)

    respond_to do |format|
      if @external_subscription.save
        format.html { redirect_to @external_subscription, notice: 'External subscription was successfully created.' }
        format.json { render :show, status: :created, location: @external_subscription }
      else
        format.html { render :new }
        format.json { render json: @external_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /external_subscriptions/1
  # PATCH/PUT /external_subscriptions/1.json
  def update
    respond_to do |format|
      if @external_subscription.update(external_subscription_params)
        format.html { redirect_to @external_subscription, notice: 'External subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @external_subscription }
      else
        format.html { render :edit }
        format.json { render json: @external_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /external_subscriptions/1
  # DELETE /external_subscriptions/1.json
  def destroy
    @external_subscription.destroy
    respond_to do |format|
      format.html { redirect_to external_subscriptions_url, notice: 'External subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_external_subscription
      @external_subscription = ExternalSubscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def external_subscription_params
      params.require(:external_subscription).permit(:project_id, :investor_id)
    end
end

app/helpers/external_subscriptions_helper.rb
module ExternalSubscriptionsHelper
end

app/views/external_subscriptions/_form.html.erb
<%= form_with(model: external_subscription, local: true) do |form| %>
  <% if external_subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(external_subscription.errors.count, "error") %> prohibited this external_subscription from being saved:</h2>

      <ul>
      <% external_subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id, id: :external_subscription_project_id %>
  </div>

  <div class="field">
    <%= form.label :investor_id %>
    <%= form.text_field :investor_id, id: :external_subscription_investor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/external_subscriptions/edit.html.erb
<h1>Editing External Subscription</h1>

<%= render 'form', external_subscription: @external_subscription %>

<%= link_to 'Show', @external_subscription %> |
<%= link_to 'Back', external_subscriptions_path %>

app/views/external_subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>External Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Investor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @external_subscriptions.each do |external_subscription| %>
      <tr>
        <td><%= external_subscription.project %></td>
        <td><%= external_subscription.investor %></td>
        <td><%= link_to 'Show', external_subscription %></td>
        <td><%= link_to 'Edit', edit_external_subscription_path(external_subscription) %></td>
        <td><%= link_to 'Destroy', external_subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New External Subscription', new_external_subscription_path %>

app/views/external_subscriptions/new.html.erb
<h1>New External Subscription</h1>

<%= render 'form', external_subscription: @external_subscription %>

<%= link_to 'Back', external_subscriptions_path %>

app/views/external_subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @external_subscription.project %>
</p>

<p>
  <strong>Investor:</strong>
  <%= @external_subscription.investor %>
</p>

<%= link_to 'Edit', edit_external_subscription_path(@external_subscription) %> |
<%= link_to 'Back', external_subscriptions_path %>