config/routes.rb
Rails.application.routes.draw do
  resources :external_subscriptions
  resources :subscriptions
  resources :investors
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/investor.rb
class Investor < ApplicationRecord
  has_many :subscriptions
  has_many :external_subscriptions
  has_many :project_investors
  has_many :projects, through: :project_investors
end

app/controllers/investors_controller.rb
class InvestorsController < ApplicationController
  before_action :set_investor, only: [:show, :edit, :update, :destroy]

  # GET /investors
  # GET /investors.json
  def index
    @investors = Investor.all
  end

  # GET /investors/1
  # GET /investors/1.json
  def show
  end

  # GET /investors/new
  def new
    @investor = Investor.new
  end

  # GET /investors/1/edit
  def edit
  end

  # POST /investors
  # POST /investors.json
  def create
    @investor = Investor.new(investor_params)

    respond_to do |format|
      if @investor.save
        format.html { redirect_to @investor, notice: 'Investor was successfully created.' }
        format.json { render :show, status: :created, location: @investor }
      else
        format.html { render :new }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investors/1
  # PATCH/PUT /investors/1.json
  def update
    respond_to do |format|
      if @investor.update(investor_params)
        format.html { redirect_to @investor, notice: 'Investor was successfully updated.' }
        format.json { render :show, status: :ok, location: @investor }
      else
        format.html { render :edit }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investors/1
  # DELETE /investors/1.json
  def destroy
    @investor.destroy
    respond_to do |format|
      format.html { redirect_to investors_url, notice: 'Investor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investor
      @investor = Investor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def investor_params
      params.require(:investor).permit(:name)
    end
end

app/helpers/investors_helper.rb
module InvestorsHelper
end

app/views/investors/_form.html.erb
<%= form_with(model: investor, local: true) do |form| %>
  <% if investor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(investor.errors.count, "error") %> prohibited this investor from being saved:</h2>

      <ul>
      <% investor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :investor_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/investors/edit.html.erb
<h1>Editing Investor</h1>

<%= render 'form', investor: @investor %>

<%= link_to 'Show', @investor %> |
<%= link_to 'Back', investors_path %>

app/views/investors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Investors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @investors.each do |investor| %>
      <tr>
        <td><%= investor.name %></td>
        <td><%= link_to 'Show', investor %></td>
        <td><%= link_to 'Edit', edit_investor_path(investor) %></td>
        <td><%= link_to 'Destroy', investor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Investor', new_investor_path %>

app/views/investors/new.html.erb
<h1>New Investor</h1>

<%= render 'form', investor: @investor %>

<%= link_to 'Back', investors_path %>

app/views/investors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @investor.name %>
</p>

<%= link_to 'Edit', edit_investor_path(@investor) %> |
<%= link_to 'Back', investors_path %>